version: "3"
networks:
  twitch:
services:
  rabbitmq:
    container_name: twitch-rabbitmq
    hostname: rabbit
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  redis:
    image: redis
    networks:
     - twitch
    ports:
      - "6379:6379"
